version: '3.9'

services:

  web-app:
    build:
      context: ./
      target: prod
    links:
      - postgresDb
    volumes:
      - .:/src
    command: npm run start
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgresDb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: takeaway-db
      NODE_ENV: prod
      PORT: 3000
    restart: on-failure
  postgresDb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: takeaway-db
      POSTGRES_HOST: postgresDb
#     volumes:
#       - db_data:/var/lib/postgresql/data
# volumes:
#   db_data: