version: '3.9'

services:

  web-app-dev:
    build:
      context: ./
      target: dev
    links:
      - postgresDbDev
    volumes:
      - .:/src
    command: npm run dev
    ports:
      - '3001:3001'
    environment:
      DB_HOST: postgresDbDev
      DB_PORT: 9001
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: takeaway-db-dev
      NODE_ENV: dev
      PORT: 3001
    restart: on-failure
  postgresDbDev:
    image: postgres:latest
    ports:
      - '9001:9001'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: takeaway-db-dev
      POSTGRES_HOST: postgresDbDev
    # volumes:
    #   - db_data:/var/lib/postgresql/data
# volumes:
#   db_data: